import type { Metadata } from "next";
import Hero from "./ui/components/home/Hero";
import { Suspense } from "react";
import Loading from "./loading";
import Networks from "./ui/components/home/Networks";
import PopularThisWeek from "./ui/components/home/PopularThisWeek";
import UpcomingMovies from "./ui/components/home/UpcomingMovies";
import SliderSkeleton from "./ui/components/skeletons/SliderSkeleton";
import PlayingNow from "./ui/components/home/PlayingNow";
import OnAirTv from "./ui/components/home/OnAirTv";

export const metadata: Metadata = {
  title: "Etfrg",
  description: "Generated by create next app",
};

export default async function Home() {
  return (
    <>
      <header className="h-screen ">
        <Suspense fallback={<Loading height="h-screen" />}>
          <Hero />
        </Suspense>
      </header>
      <main>
        <section>
          <Suspense
            fallback={
              <SliderSkeleton
                height={"h-[100px]"}
                width={"w-[150px]"}
                times={7}
              />
            }
          >
            <Networks />
          </Suspense>
        </section>
        <section>
          <div className="container flex flex-col gap-6">
            <h4 className=" text-2xl font-bold text-white">
              Popular of the week
            </h4>
            <div>
              <Suspense
                fallback={
                  <SliderSkeleton
                    height={"h-[146px]"}
                    width={"w-[320px]"}
                    times={4}
                  />
                }
              >
                <PopularThisWeek />
              </Suspense>
            </div>
          </div>
        </section>
        <section>
          <div className="container flex flex-col gap-6">
            <h4 className=" text-2xl font-bold text-white">Upcoming Movies</h4>
            <div>
              <Suspense
                fallback={
                  <SliderSkeleton
                    height={"h-[532px]"}
                    width={"w-[320px]"}
                    times={4}
                  />
                }
              >
                <UpcomingMovies />
              </Suspense>
            </div>
          </div>
        </section>
        <section>
          <div className="container flex flex-col gap-6">
            <h4 className=" text-2xl font-bold text-white">
              Movies Playing Now
            </h4>
            <div>
              <Suspense
                fallback={
                  <SliderSkeleton
                    height={"h-[532px]"}
                    width={"w-[320px]"}
                    times={4}
                  />
                }
              >
                <PlayingNow />
              </Suspense>
            </div>
          </div>
        </section>
        <section>
          <div className="container flex flex-col gap-6">
            <h4 className=" text-2xl font-bold text-white">On The Air Tv</h4>
            <div>
              <Suspense
                fallback={
                  <SliderSkeleton
                    height={"h-[532px]"}
                    width={"w-[320px]"}
                    times={4}
                  />
                }
              >
                <OnAirTv />
              </Suspense>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
